### ISSUE TITLE
Schedule adherence map does not work if all vehicles are not assigned.

### ISSUE THREAD

**Issue by scrudden** [TheTransitClock/transitime#122]
The `distanceAlongTrip: NaN` in the json returned by vehiclesDetails api call is not valid json. If all vehicles are assigned distanceAlongTrip is set so this is not an issue.

I think vehiclesDetails could do with a parameter to return only currently assigned vehicles.

**Comment by vsperez** [comment]
Three variables has the same behavior if trip is null: distanceToNextStop, distanceOfNextStopFromTripStart and distanceAlongTrip. This ones should be null in order to have a valid JSON, so changed them from double to Double and set them to null. @scrudden  Do you see any issues that this might cause?

**Comment by nselikoff** [comment]
Checking in on this one as I'm getting parse errors from ingesting the `vehiclesDetails` API endpoint in another system. 

From what I can see, the only one of these three variables that is used by any system within TheTransitClock (besides the `IpcVehicleComplete` class itself, is `distanceAlongTrip`, within the Synoptic view you created @vsperez. I like your proposal to switch these to `Double` and set them to null.

**Comment by vsperez** [comment]
Hi guys,

As far as I remember, this was already fixed (exactly in the way @nselikoff  proposed). https://github.com/vsperez/transitime/tree/tc_issue_122

Best regards
Vicente

**Comment by scrudden** [comment]
This change has a corresponding pull request #124.

**Comment by nselikoff** [comment]
Looks like PR #124 incorporates both changes - nullifying the variables, and adding the `assigned` parameter to the API endpoint. Might I suggest calling it `onlyAssigned` or `excludeUnassigned` or something to that effect? Otherwise if you're querying the API with `&assigned=false` you might expect to only get vehicles which are unassigned (versus all vehicles).

**Comment by vsperez** [comment]
Hi Nathan,

Actually that is the idea of the parameter, the name might not be the best. The filter is:
if((assigned && vehicle.getTripId()!=null ) || !assigned)

If parameter assigned is true it will return only assignedVehicles, otherwise all.

I will fix the typo as soon as possible.

**Comment by vsperez** [comment]
Hi,

I fixed the typo and changed the name of the paramter from assigned to onlyAssigned.

**Comment by scrudden** [comment]
Fixed in #142 and merged.
