### ISSUE TITLE
Recommended schedule for running UpdateTravelTimes

### ISSUE THREAD

**Issue by nselikoff** [TheTransitClock/transitime#51]
Based on looking at https://github.com/open-austin/transitime-docker/issues/3 I can see how to run UpdateTravelTimes, and that it can take either one date (interpreted as start and end) or two separate start and end dates.

What's the recommended schedule for running UpdateTravelTimes, and do you typically run for one day or over a span of days?

**Comment by scrudden** [comment]
Hi Nathan,

This is a good question.

The result I believe you are looking for is the best quality predictions and the answer to what gives this is not so simple and can be dependent on the characteristics of the route you are working with.

If you do not run UpdateTravelTimes the default prediction implementation (PredictionGeneratorDefaultImpl) will use a sum of scheduled travel times and scheduled dwell times to predict the arrival times at upcoming stops. This can produce decent results.

So, to get something that is better than the schedule you will need enough sample data so that the "average" (not just a simple average, removes outlying values and dodgy data) travel times and dwell times used are statistically significant. I would run this over the full sample set in one run of UpdateTravelTimes.

The fact this update has to be done manually is one of the drawbacks of the default prediction implementation.

Cheers,

Sean.

**Comment by nselikoff** [comment]
Thanks for the explanation @scrudden - that is indeed the result I'm looking for. Is there a rule of thumb in your experience when it comes to "enough sample data" to get to statistical significance? For example, I'm working with a route right now that is very sparse... there are only 23 trips a week.

**Comment by scrudden** [comment]
Without knowing the schedule I would guess perhaps 20 independent sets of data for each trip_id. If you work up to this you will see the values used for each stop path travel time level off and at that point you should have enough.

**Comment by scrudden** [comment]
@nselikoff Can this issue be closed?

**Comment by nselikoff** [comment]
Yes, thanks for the additional guidance @scrudden

**Comment by nselikoff** [comment]
Hi @scrudden, I'm reopening this issue to get a little more help on running UpdateTravelTimes. I have run the UpdateTravelTimes.jar on the command line, but still have some questions:

1. Should UpdateTravelTimes be run for just one day? Or for a range of days? If a range, how long of a range?
2. Besides the start and end date, are there other important config params to be aware of for UpdateTravelTimes?
3. How often should UpdateTravelTimes be run?
4. What should I look for in the database to see that it was run correctly and is doing what it is supposed to?

Thanks!

**Comment by scrudden** [comment]
To check that UpdateTravelTimes has run successfully you can run this query. If the only result is SCHED then it has not run correctly (or perhaps there was no data in the date range specified for it to process).

```
select howset, count(*) from traveltimesforstoppaths group by howset;
 howset |  count  
--------+---------
 AVL    |    1450
 SERVC  |    1399
 SCHED  | 1939017
 TRIP   |    1437
(4 rows)

```
The description of each of these values can be found here in the code comments.

https://github.com/TheTransitClock/transitime/blob/ca67e757d9e125d193cdc281fc86b337ce96a9fe/transitclock/src/main/java/org/transitclock/db/structs/TravelTimesForStopPath.java#L146-L180

**Comment by scrudden** [comment]
You need to restart Core for it to use the newly processed travel times for generating predictions.

**Comment by scrudden** [comment]
If this is to be run regularly I would run it once a week for a rolling period covering the last 28 days. On larger systems there may be performance issues with this. 

https://github.com/TheTransitClock/transitime/blob/ca67e757d9e125d193cdc281fc86b337ce96a9fe/transitclock/src/main/java/org/transitclock/applications/UpdateTravelTimes.java#L46-L54

This is one of the motivations for adding the Kalman Filter for travel times and RLS algorithm for dwell times to TheTransitClock. These both update as the system runs.

**Comment by scrudden** [comment]
@nselikoff Can I close this issue again?

**Comment by nselikoff** [comment]
Yes, thanks @scrudden
